package zhou.unit3;

import java.util.Scanner;

/** AnimalguessingGame.java
 * <p> This program plays a guessing game with the user.
 * <b> The program will start randomly guessing from a list of answers until it guesses correctly. The user will type in
 * whether or not the answer is correct.
 * <b> Date created: November 25, 2019
 * @author Sarah Zhou
 *
 */

public class AnimalGeussingGame {

	/**
	 * This is the entry point to the program.
	 * @param args
	 */
	public static void main(String [] args) {

		// Variables
		String[] animals = {"mouse", "cow", "tiger", "rabbit", "seahorse", "snake", "goat", "horse", "monkey", "pig", "dog", "chicken", "cat", "fly",
				"donkey", "giraffe", "porcupine", "hedgehog", "kangaroo", "spider", "owl", "wolf"};

		int count = animals.length;
		int length = count;
		int tries;
		int num = 0;
		String userAnswer = "no";
		String guess;

		boolean notTried = true;

		// Scanner
		Scanner sc = new Scanner(System.in);

		// Opening line for user to start playing.
		System.out.println("Let's play a game. Type in 'yes' or 'no' whenever I guess. Think of an animal. ");

		/**
		 * A while loop that runs while the count is greater than 0, and the user's answer is no.
		 */
		while (count > 0 && userAnswer.equalsIgnoreCase("no")) {

			// Generates a pseudo-random number within the length of the animals array, and rounds it into a integer.
			num = (int) (Math.random() * animals.length);

			// Assigns the random number generated by num into index of animal, and assigns the value in the index to the variable guess.
			guess = animals[num];

			// If the guess has the value of null, the boolean notTried becomes false.
			if (guess == null) {
				notTried = false;
			}

			/**
			 * While loop that runs while the boolean notTried is
			 */
			while (!notTried) {
				num = (int) (Math.random() * animals.length);
				guess = animals[num];
				if (guess == null) {
					notTried = false;
				}
				else {
					notTried = true;
				}
			}

			animals[num] = null;

			System.out.println("Is it a " + guess + "?");
			userAnswer = sc.next();

			count --;
		}

		if (count <= 0) {
			System.out.println("I can't guess youer animal! I lose.");
		}

		tries = length - count;

		if (userAnswer.equalsIgnoreCase("yes")) {
			System.out.println("I win!! It took me " + tries + " tries!");
		}
	}

}
